// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OptiFeed.Persistence.Context;

#nullable disable

namespace OptiFeed.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241029180038_RationFeedItems_Model_Updated")]
    partial class RationFeedItems_Model_Updated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OptiFeed.Core.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("DailyMilkYield")
                        .HasColumnType("float");

                    b.Property<double>("LiveWeight")
                        .HasColumnType("float");

                    b.Property<double>("MilkFat")
                        .HasColumnType("float");

                    b.Property<double>("MilkProtein")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("OptiFeed.Core.Models.Feed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("ADFContent")
                        .HasColumnType("float");

                    b.Property<double>("CostPerKg")
                        .HasColumnType("float");

                    b.Property<double>("DryMatter")
                        .HasColumnType("float");

                    b.Property<double>("EnergyContent")
                        .HasColumnType("float");

                    b.Property<double>("MaxUsage")
                        .HasColumnType("float");

                    b.Property<double>("MinUsage")
                        .HasColumnType("float");

                    b.Property<double>("NDFContent")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProteinContent")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Feeds");
                });

            modelBuilder.Entity("OptiFeed.Core.Models.FeedStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("FeedId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FeedId")
                        .IsUnique();

                    b.ToTable("FeedStocks");
                });

            modelBuilder.Entity("OptiFeed.Core.Models.Ration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.ToTable("Rations");
                });

            modelBuilder.Entity("OptiFeed.Core.Models.RationDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RationId")
                        .HasColumnType("int");

                    b.Property<double>("TotalCost")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("RationId")
                        .IsUnique();

                    b.ToTable("RationDetails");
                });

            modelBuilder.Entity("OptiFeed.Core.Models.RationFeedItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FeedName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PricePerKg")
                        .HasColumnType("float");

                    b.Property<int>("RationDetailId")
                        .HasColumnType("int");

                    b.Property<double>("UsageAmountKg")
                        .HasColumnType("float");

                    b.Property<double>("UsagePercentage")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("RationDetailId");

                    b.ToTable("RationFeedItems");
                });

            modelBuilder.Entity("OptiFeed.Core.Models.FeedStock", b =>
                {
                    b.HasOne("OptiFeed.Core.Models.Feed", "Feed")
                        .WithOne("FeedStock")
                        .HasForeignKey("OptiFeed.Core.Models.FeedStock", "FeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feed");
                });

            modelBuilder.Entity("OptiFeed.Core.Models.Ration", b =>
                {
                    b.HasOne("OptiFeed.Core.Models.Animal", null)
                        .WithMany("Rations")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OptiFeed.Core.Models.RationDetail", b =>
                {
                    b.HasOne("OptiFeed.Core.Models.Ration", null)
                        .WithOne("RationDetail")
                        .HasForeignKey("OptiFeed.Core.Models.RationDetail", "RationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OptiFeed.Core.Models.RationFeedItem", b =>
                {
                    b.HasOne("OptiFeed.Core.Models.RationDetail", "RationDetail")
                        .WithMany("FeedItems")
                        .HasForeignKey("RationDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RationDetail");
                });

            modelBuilder.Entity("OptiFeed.Core.Models.Animal", b =>
                {
                    b.Navigation("Rations");
                });

            modelBuilder.Entity("OptiFeed.Core.Models.Feed", b =>
                {
                    b.Navigation("FeedStock");
                });

            modelBuilder.Entity("OptiFeed.Core.Models.Ration", b =>
                {
                    b.Navigation("RationDetail");
                });

            modelBuilder.Entity("OptiFeed.Core.Models.RationDetail", b =>
                {
                    b.Navigation("FeedItems");
                });
#pragma warning restore 612, 618
        }
    }
}
